apiVersion: apps/v1
kind: Deployment
metadata:
  name: load
  labels:
    app: load
spec:
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  replicas: 4
  selector:
    matchLabels:
      app: load
  template:
    metadata:
      labels:
        app: load
    spec:
      containers:
      - name: load
        image: europe-central2-docker.pkg.dev/irio-linter/irio/load
        args: ["-target-addr=10.116.15.186:20000"]
        resources:
          requests:
            memory: "64Mi"
            cpu: "400m"
          limits:
            memory: "64Mi"
            cpu: "400m"
