apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-service
  labels:
    app: loadbalancer
spec:
  type: LoadBalancer
  ports:
  - name: data
    port: 20000
    targetPort: 20000
    protocol: TCP
  selector:
    app: loadbalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadbalancer
  labels:
    app: loadbalancer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: loadbalancer
  template:
    metadata:
      labels:
        app: loadbalancer
        xD: loadbalancer
    spec:
      containers:
      - name: loadbalancer
        image: europe-central2-docker.pkg.dev/irio-linter/irio/loadbalancer:latest
        ports:
        - containerPort: 10000
          name: admin
        - containerPort: 20000
          name: data
        args: ["-data-addr=:20000", "-admin-addr=:10000"]
        livenessProbe:
          httpGet:
            path: "/health"
            port: 20000
