apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-service
  labels:
    app: loadbalancer
spec:
  type: LoadBalancer
  ports:
  - name: http-port
    port: 22222
    targetPort: 22222
    protocol: TCP
  - name: grpc-port
    port: 33333
    targetPort: 33333
    protocol: TCP
  selector:
    app: loadbalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadbalancer
  labels:
    app: loadbalancer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: loadbalancer
  template:
    metadata:
      labels:
        app: loadbalancer
        xD: loadbalancer
    spec:
      containers:
      - name: loadbalancer
        image: loadbalancer_container
        imagePullPolicy: Never
        ports:
        - containerPort: 22222
        - containerPort: 33333
