apiVersion: v1
kind: Service
metadata:
  name: loadbalancer
  labels:
    app: loadbalancer
spec:
  type: LoadBalancer
  ports:
  - name: data
    port: 20000
    targetPort: 20000
    protocol: TCP
  selector:
    app: loadbalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadbalancer
  labels:
    app: loadbalancer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: loadbalancer
  template:
    metadata:
      labels:
        app: loadbalancer
        xD: loadbalancer
    spec:
      tolerations:
      - key: reserved-pool
        operator: Equal
        value: "true"
        effect: NoSchedule
      containers:
      - name: loadbalancer
        image: europe-central2-docker.pkg.dev/irio-test-338916/irio-test/loadbalancer:latest
        ports:
        - containerPort: 10000
          name: admin
        - containerPort: 20000
          name: data
        args: ["-data-addr=:20000", "-admin-addr=:10000"]
        livenessProbe:
          httpGet:
            path: "/health"
            port: 20000
        resources:
          requests:
            memory: "64Mi"
            cpu: "500m"
          limits:
            memory: "64Mi"
            cpu: "500m"
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: loadbalancer
spec:
  minReplicas: 3
  maxReplicas: 20
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: loadbalancer
  targetCPUUtilizationPercentage: 75
