version: '2'

services:
  etcd:
    image: docker.io/bitnami/etcd:3
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    ports:
      - 2379:2379
  machine-manager:
    depends_on:
      - etcd
    build:
      context: .
      target: test
